version: '3.8'
services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./database.sqlite:/app/database.sqlite
      - ./second_database.sqlite:/app/second_database.sqlite
    environment:
      NODE_ENV: development
      PORT: 3000

# volumes:
#   src:
